[project]
name = "icd10-codes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "polars>=1.36.1",
    "python-dotenv>=1.2.1",
]
